-- This module is the root of the PAdicHodgeRealizationsCanonicalLaneLean Lean proof package.
import PAdicHodgeRealizationsCanonicalLaneLean.Basic
import PAdicHodgeRealizationsCanonicalLaneLean.SourcePackage
import PAdicHodgeRealizationsCanonicalLaneLean.SourceDependencies
import PAdicHodgeRealizationsCanonicalLaneLean.Formalization
import PAdicHodgeRealizationsCanonicalLaneLean.ReviewerBridge
import PAdicHodgeRealizationsCanonicalLaneLean.TheoremStatement
import PAdicHodgeRealizationsCanonicalLaneLean.MathlibObjects
import PAdicHodgeRealizationsCanonicalLaneLean.AdmissibleClass
import PAdicHodgeRealizationsCanonicalLaneLean.Projection
import PAdicHodgeRealizationsCanonicalLaneLean.BridgeLemmas
import PAdicHodgeRealizationsCanonicalLaneLean.GateLemmas
import PAdicHodgeRealizationsCanonicalLaneLean.FinalTheorem
import PAdicHodgeRealizationsCanonicalLaneLean.MathlibStatement
